config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
        mount BrowseEverything::Engine => '/browse'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users,
             skip: [:registrations],
             controllers: {
               omniauth_callbacks: 'vdc/omniauth_callbacks',
               registrations:      'vdc/registrations',
               sessions: 'users/sessions'}

  # Update devise routes to only allow new/create/cancel
  # for new user registrations. The other operations will only
  # be allowed by the admin for now
  as :user do
    get   '/users/sign_up', to: 'vdc/registrations#new', as: :new_user_registration
    post  '/user', to: 'vdc/registrations#create', as: :user_registration
    get   '/users/cancel', to: 'vdc/registrations#cancel', as: :cancel_user_registration
  end

  authenticate :user, ->(user) { user.groups.include?("admin") } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Qa::Engine => '/authorities'
  mount Hyrax::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'hyrax/homepage#index'
  curation_concerns_basic_routes
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  namespace :vdc do
    resources :usages, only: [:index, :new, :create]
  end
end

Hyrax::Engine.routes.draw do
  namespace :admin do
    namespace :vdc do
      post 'pending_registrations/approve_user'
      resources :pending_registrations, only: [:index]
      if Rails.env.development?
        resources :people
      else
        resources :people, except: [:index]
      end
    end
    resources :users, only: [:edit, :update]
  end

  match "/download_cv/:id/", controller: "admin/users", action: "download_cv", via: :get
  get 'download/usage/:id', to: 'downloads#download_usage', as: :download_usage

  namespace :vdc do
    resources :usages, only: [:index, :new, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Connects this user object to Hydra behaviors.
  include Hydra::User
  # Connects this user object to Hyrax behaviors.
  include Hyrax::User
  include Hyrax::UserUsageStats

  #validates :first_name, presence: true
  #validates :last_name, presence: true
  #validates :email, presence: true
  #validates :organization, presence: true
  #validates :position, presence: true
  #validates :discipline, presence: true
  #validates :orcid, presence: true
  #validates :email, presence: true

  if Blacklight::Utils.needs_attr_accessible?
    attr_accessible :email, :password, :password_confirmation
  end
  # Connects this user object to Blacklights Bookmarks.
  include Blacklight::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :cv_file, CvFileUploader
  validates_integrity_of :cv_file # Checks for type whitelist
  validates_processing_of :cv_file

  serialize :discipline

  scope :registered, ->() { where(guest: false).where(approved: true) }
  scope :not_approved, ->() {  where(guest: false).where(approved: false) }

  def display_name
    return to_s if last_name.blank? || first_name.blank?
    "#{last_name}, #{first_name}"
  end

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier for
  # the account.
  # TODO: Need to eventually change the depositor email used in solr searches.
  #       Should switch to using the uuid or something else that can't potentially
  # change in the future.
  def to_s
    email
  end

  # Method to help with admin user registration approval
  def active_for_authentication?
    super && approved?
  end

  # Method to help with  admin user registration approval
  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def self.from_omniauth(auth)
    Rails.logger.error("omniauth: #{auth}")
    find_by(email: auth.info.email)
  end

  validate :validate_organization
  def validate_organization
    #TODO: Should I make 'other' a constant somewhere?
    if (organization == 'other') and (organization_other.strip == '')
      errors.add(:organization_other, 'You must provide a description of your organization if "Other" is selected.')
    end
  end

  after_validation :check_url_protocols
  def check_url_protocols
    # TODO: There's gotta be a more efficient way to do this...

    self.website = add_url_protocol(self.website)
    self.cv_link = add_url_protocol(self.cv_link)
    self.sites_open_science_framework_url = add_url_protocol(self.sites_open_science_framework_url)
    self.sites_researchgate_url = add_url_protocol(self.sites_researchgate_url)
    self.sites_linkedin_url = add_url_protocol(self.sites_linkedin_url)
    self.sites_vivo_url = add_url_protocol(self.sites_vivo_url)
    self.sites_institutional_repo_url = add_url_protocol(self.sites_institutional_repo_url)
    self.sites_other_url = add_url_protocol(self.sites_other_url)
  end

  def add_url_protocol(url)
    return url if !url || url.blank?
    return url if url[/\Ahttp/]
    return "http://#{url}"
  end

  #TODO: Should this be in a controller instead?
  after_create :send_admin_mail_after_registration
  def send_admin_mail_after_registration
    if !self.guest
      AdminMailer.new_user_waiting_for_approval(self).deliver
      AdminMailer.new_user_waiting_for_approval_admin_notification(self).deliver
    end
  end

  def guest=(value)
    if !value
      AdminMailer.new_user_waiting_for_approval(self).deliver
      AdminMailer.new_user_waiting_for_approval_admin_notification(self).deliver
    end
    super(value)
  end

  def password_required?
    if !persisted?
      false
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def recent_users(start_date, end_date = nil)
    end_date ||= DateTime.current # doing or eq here so that if the user passes nil we still get now
    User.where(created_at: start_date..end_date).where(approved: true)
  end

  # NOTE: discipline is set via a multi-select form input field.
  #       These multi-selects always send a hidden blank field
  #       which muddles things when trying to save and display values.
  #       I'm not sure how to get around this, but for now, I'm
  #       putting in code to remove blank fields before validation
  #
  #       https://stackoverflow.com/questions/8929230/why-is-the-first-element-always-blank-in-my-rails-multi-select-using-an-embedde
  #before_validation do |user|
    #byebug
    #self.discipline = self.discipline.reject(&:blank?) if self.discipline #NG
    #user.discipline.reject!(&:blank?) if user.discipline #NG
  #end

end

app/controllers/hyrax/admin/users_controller.rb
# Modified from Hyrax Gem 1.0.2
# Updated to override from Hyrax Gem 2.0.0

module Hyrax
  class Admin::UsersController < ApplicationController
    include Hyrax::Admin::UsersControllerBehavior

    def edit
      @user = ::User.find_by(id: params[:id])
    end

    def update
      @user = ::User.find_by(id: params[:id])
      if @user.update(user_admin_params)
        if @user.identifier_system.nil?
          # The user has not been approved yet.
          redirect_to hyrax.admin_vdc_pending_registrations_path, notice: "Updated registration for #{@user.email}"
        else
          # The user has been approved in the past.
          redirect_to hyrax.admin_users_path, notice: "Updated registration for #{@user.email}"
        end
      else
        render 'edit'
      end
    end

    def download_cv
      @user = ::User.find_by(id: params[:id])
      send_file @user.cv_file.current_path if !@user.cv_file.file.nil?
    end

    private
 
      def user_admin_params
        params.require(:user).permit(key_attributes)
      end

      # TODO: This is almost a copy of the registrations_controller key attributes.
      #       Is there a way to avoid duplication?
      # TODO: Find a better way to update :edu_person_principal_name or
      #       to not accidentally overwrite it. (taken out of whitelist for now)
      def key_attributes
        [:vdc_referral_method,:vdc_referral_method_other,:first_name, :last_name, 
         :organization, :organization_other, 
         :department,
         :position, :position_other, 
         {:discipline => []}, :discipline_other, 
         :orcid,
         :address, :email,
         :cv_link, :cv_file, 
         :website,
         :sites_open_science_framework, :sites_open_science_framework_url,
         :sites_researchgate, :sites_researchgate_url,
         :sites_linkedin, :sites_linkedin_url,
         :sites_vivo, :sites_vivo_url,
         :sites_institutional_repo, :sites_institutional_repo_url,
         :sites_other, :sites_other_url,
         :usage_deposit_files, :usage_use_files, :usage_use_tools_on_vdc_data,
         :usage_use_tools_on_external_data, :usage_contact_others,
         :usage_description,:usage_duration]
      end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController

   protected
   def after_sign_in_path_for(resource)
    hyrax.dashboard_profile_path(resource)
   end
  end
end

app/views/hyrax/admin/users/edit.html.erb
<h2>Edit Registration for: <%= @user %></h2>

<%= simple_form_for(:user, url: admin_user_path(@user, id: @user.id), method: :patch) do |f| %>

  <%= render 'registration_form', f: f %>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>

<% end %>

app/views/hyrax/admin/users/index.html.erb
<%# Modified from Hyrax Gem 1.0.2 %>

<% content_for :page_header do %>
  <h1><span class="fa fa-user"></span> <%= t('hyrax.admin.users.index.title') %></h1>
<% end %>

<div class="panel panel-default users-listing">
  <div class="panel-heading">
      <%= t('hyrax.admin.users.index.describe_users_html', count: @presenter.user_count) %>
  </div>

  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped datatable">
        <thead>
          <tr>
            <th></th>
            <th><%= t('.id_label') %></th>
            <th><%= t('.role_label') %></th>
            <th><%= t('.access_label') %></th>
            <th><%= t('.operations_label') %></th>
          </tr>
        </thead>
        <tbody>
          <% @presenter.users.each do |user| %>
            <tr>
              <td><%= link_to hyrax.dashboard_profile_path(user) do %>
                    <%= image_tag(user.avatar.url(:thumb), width: 30) if user.avatar.file %>
                  <% end %>
              </td>
              <br>
              <td><%= link_to user.email, hyrax.dashboard_profile_path(user) %></td>
              <td><% roles = @presenter.user_roles(user) %>
                  <ul><% roles.each do |role| %>
                    <li><%= role %></li>
                    <% end %>
                  </ul>
              </td>
              <td>
                <%# in the case that a user is created who never signs in, this is necessary %>
                <relative-time datetime="<%= @presenter.last_accessed(user).getutc.iso8601 %>" title="<%= @presenter.last_accessed(user).to_formatted_s(:standard) %>">
                  <%= @presenter.last_accessed(user).to_formatted_s(:long_ordinal) %>
                </relative-time>
              </td>
              <td>
                <%= link_to 'Update Registration', edit_admin_user_path(id: user.id) %> |
                <% if !user.identifier_system.nil? %>
                  <%= link_to 'Sync Person', admin_vdc_person_path(user_id: user.id, id: user.identifier_system), method: :patch %>
                <% else %>
                  <%= link_to 'Create Person', admin_vdc_people_path(user_id: user.id), method: :post %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>